### ISSUE TITLE
[UCP Bug Report] Bug Firstname Lastname Character

### ISSUE THREAD

**Issue by AzharHrj** [RedTimerIndonesia/issue-tracker#2]
### Nama UCP

ayonima

### Deskripsi Bug

bugnya adalah pada saat buat character, dan mengisi Firtsname dan lastname, di bagian lastname character kosong alias jadi kek gini doang, Andreas_ yang seharusnya Andreas_Ayonima

### Langkah reproduksi bug

pas register dan membuat character

### Barang bukti

![image](https://user-images.githubusercontent.com/75940399/156008418-7196a5b8-5561-417a-b285-7b47a8cea31e.png)

### Info tambahan

kami para player mengerti, ini baru development, jadi belum sempurna...

**Comment by SanityZeroPercent** [comment]
![image](https://user-images.githubusercontent.com/27568445/156020930-a0f0328e-600c-4579-a59c-173824f9e4da.png)
Fixed!
